apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  ENVIRONMENT: production
  GOOGLE_CLOUD_PROJECT: __PROJECT_ID__
  IDENTITY_PROJECT_ID: __PROJECT_ID__
  KMS_KEY_NAME: __KMS_KEY_NAME__
  STATIC_DIR: /app/frontend/dist
  COOKIE_SECURE: "true"
  DEV_AUTH_ENABLED: "false"
  FETCHER_URL: https://fetcher:8443
  FETCHER_CA_FILE: /var/run/phishguard/jobs/mtls-ca-cert
  FETCHER_CERT_FILE: /var/run/phishguard/jobs/mtls-client-cert
  FETCHER_KEY_FILE: /var/run/phishguard/jobs/mtls-client-key
  JOB_CONCURRENCY: "10"
  NOTICE_VERSION: "2026-07-22"
  DB_NAME: phishguard
  CLOUD_SQL_CONNECTION_NAME: __CLOUD_SQL_CONNECTION_NAME__
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web
  annotations:
    iam.gke.io/gcp-service-account: phishguard-web@__PROJECT_ID__.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jobs
  annotations:
    iam.gke.io/gcp-service-account: phishguard-jobs@__PROJECT_ID__.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: migrate
  annotations:
    iam.gke.io/gcp-service-account: phishguard-migrate@__PROJECT_ID__.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fetcher
automountServiceAccountToken: false
