apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: web-secrets
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/__PROJECT_ID__/secrets/phishguard-app-hmac-key/versions/latest"
        path: "app-hmac-key"
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: migrate-secrets
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/__PROJECT_ID__/secrets/phishguard-db-migrator-password/versions/latest"
        path: "db-migrator-password"
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: jobs-secrets
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/__PROJECT_ID__/secrets/phishguard-app-hmac-key/versions/latest"
        path: "app-hmac-key"
      - resourceName: "projects/__PROJECT_ID__/secrets/phishguard-web-risk-api-key/versions/latest"
        path: "web-risk-api-key"
      - resourceName: "projects/__PROJECT_ID__/secrets/phishguard-mtls-ca-cert/versions/latest"
        path: "mtls-ca-cert"
      - resourceName: "projects/__PROJECT_ID__/secrets/phishguard-mtls-client-cert/versions/latest"
        path: "mtls-client-cert"
      - resourceName: "projects/__PROJECT_ID__/secrets/phishguard-mtls-client-key/versions/latest"
        path: "mtls-client-key"
